# Generated by Django 5.2.17 on 2026-09-27 17:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="número")),
                (
                    "title",
                    models.CharField(blank=True, max_length=120, verbose_name="título"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Publicada"),
                            ("hidden", "Oculta por moderación"),
                        ],
                        default="published",
                        max_length=12,
                    ),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="me gusta"),
                ),
                (
                    "comment_count",
                    models.PositiveIntegerField(default=0, verbose_name="comentarios"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
            ],
            options={
                "verbose_name": "capítulo",
                "verbose_name_plural": "capítulos",
                "ordering": ["series", "number"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200, verbose_name="pregunta")),
                ("answer", models.TextField(max_length=2000, verbose_name="respuesta")),
                ("active", models.BooleanField(default=True, verbose_name="activa")),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "pregunta frecuente",
                "verbose_name_plural": "preguntas frecuentes",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="título")),
                ("summary", models.CharField(max_length=300, verbose_name="resumen")),
                (
                    "image_url",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="imagen"
                    ),
                ),
                ("link_url", models.URLField(blank=True, verbose_name="enlace")),
                ("active", models.BooleanField(default=True, verbose_name="visible")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
            ],
            options={
                "verbose_name": "proyecto DBP",
                "verbose_name_plural": "proyectos DBP",
                "ordering": ["order", "-created"],
            },
        ),
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="título")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="descripción"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ilustracion", "Ilustración"),
                            ("comic", "Cómic"),
                            ("manga", "Manga"),
                            ("historieta", "Historieta"),
                            ("boceto", "Boceto"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="categoría",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        max_length=1000, verbose_name="enlace de la imagen"
                    ),
                ),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="etiquetas"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Publicada"),
                            ("hidden", "Oculta por moderación"),
                        ],
                        db_index=True,
                        default="published",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "moderation_note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nota de moderación"
                    ),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="me gusta"),
                ),
                (
                    "comment_count",
                    models.PositiveIntegerField(default=0, verbose_name="comentarios"),
                ),
                (
                    "save_count",
                    models.PositiveIntegerField(default=0, verbose_name="guardados"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="creada"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="actualizada"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artworks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "obra",
                "verbose_name_plural": "obras",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ChapterPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("image_url", models.CharField(max_length=1000)),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="ilustra.chapter",
                    ),
                ),
            ],
            options={
                "verbose_name": "página",
                "verbose_name_plural": "páginas",
                "ordering": ["chapter", "order"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=1000, verbose_name="texto")),
                (
                    "status",
                    models.CharField(
                        choices=[("visible", "Visible"), ("hidden", "Oculto")],
                        db_index=True,
                        default="visible",
                        max_length=12,
                    ),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="me gusta"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "artwork",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="ilustra.artwork",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="ilustra.chapter",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="ilustra.comment",
                    ),
                ),
            ],
            options={
                "verbose_name": "comentario",
                "verbose_name_plural": "comentarios",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="ModeratorScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Vacío = todas. Ej.: ["manga", "comic"]',
                        verbose_name="categorías a cargo",
                    ),
                ),
                (
                    "can_moderate_artworks",
                    models.BooleanField(
                        default=True, verbose_name="moderar obras y series"
                    ),
                ),
                (
                    "can_moderate_comments",
                    models.BooleanField(
                        default=True, verbose_name="moderar comentarios"
                    ),
                ),
                (
                    "can_manage_reports",
                    models.BooleanField(
                        default=True, verbose_name="gestionar reportes"
                    ),
                ),
                (
                    "can_suspend_users",
                    models.BooleanField(
                        default=False, verbose_name="suspender usuarios"
                    ),
                ),
                (
                    "can_manage_projects",
                    models.BooleanField(
                        default=False, verbose_name="gestionar proyectos DBP y FAQ"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="activo")),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderator_scope",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "moderador",
                "verbose_name_plural": "moderadores",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("like", "Me gusta"),
                            ("comment", "Comentario"),
                            ("reply", "Respuesta"),
                            ("follow", "Seguidor"),
                            ("chapter", "Nuevo capítulo"),
                            ("dbp", "Aviso DBP"),
                        ],
                        max_length=10,
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=200)),
                ("read", models.BooleanField(db_index=True, default=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "artwork",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ilustra.artwork",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ilustra.chapter",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notificación",
                "verbose_name_plural": "notificaciones",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_sub",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "handle",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9._]{3,30}$",
                                "Usá de 3 a 30 caracteres: minúsculas, números, punto o guion bajo.",
                            )
                        ],
                        verbose_name="usuario",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=80, verbose_name="nombre"),
                ),
                ("avatar_url", models.URLField(blank=True, max_length=1000)),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ubicación"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="Correo, web o red social que el artista quiere mostrar.",
                        max_length=200,
                        verbose_name="contacto público",
                    ),
                ),
                (
                    "disciplines",
                    models.JSONField(
                        blank=True, default=list, verbose_name="disciplinas"
                    ),
                ),
                (
                    "is_artist",
                    models.BooleanField(default=False, verbose_name="es artista"),
                ),
                (
                    "accent",
                    models.CharField(
                        choices=[
                            ("violet", "Violeta"),
                            ("yellow", "Amarillo"),
                            ("sky", "Celeste"),
                            ("coral", "Coral"),
                        ],
                        default="violet",
                        max_length=10,
                        verbose_name="acento del muro",
                    ),
                ),
                (
                    "cover_url",
                    models.URLField(
                        blank=True, max_length=1000, verbose_name="portada"
                    ),
                ),
                (
                    "suspended",
                    models.BooleanField(default=False, verbose_name="suspendido"),
                ),
                ("suspended_reason", models.CharField(blank=True, max_length=200)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "perfil",
                "verbose_name_plural": "perfiles",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("artwork", "Obra"),
                            ("chapter", "Capítulo"),
                            ("comment", "Comentario"),
                            ("user", "Usuario"),
                        ],
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                ("target_id", models.PositiveBigIntegerField()),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("copia", "No es obra del autor / plagio"),
                            ("ofensivo", "Contenido ofensivo"),
                            ("spam", "Spam"),
                            ("sensible", "Contenido sensible sin aviso"),
                            ("otro", "Otro"),
                        ],
                        max_length=10,
                        verbose_name="motivo",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="detalle"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Abierto"),
                            ("resolved", "Resuelto"),
                            ("dismissed", "Descartado"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "reporte",
                "verbose_name_plural": "reportes",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="título")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="descripción"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("comic", "Cómic"),
                            ("manga", "Manga"),
                            ("historieta", "Historieta"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="categoría",
                    ),
                ),
                (
                    "cover_url",
                    models.CharField(max_length=1000, verbose_name="portada"),
                ),
                ("cover_width", models.PositiveIntegerField(default=0)),
                ("cover_height", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Publicada"),
                            ("hidden", "Oculta por moderación"),
                        ],
                        db_index=True,
                        default="published",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                ("moderation_note", models.CharField(blank=True, max_length=200)),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "serie",
                "verbose_name_plural": "series",
                "ordering": ["-updated"],
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="ilustra.series",
            ),
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="ilustra.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "comment"), name="commentlike_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("follower", "following"), name="follow_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("follower", models.F("following")), _negated=True
                        ),
                        name="follow_not_self",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "artwork",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="ilustra.artwork",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="ilustra.chapter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("artwork__isnull", False)),
                        fields=("user", "artwork"),
                        name="like_unique_artwork",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("chapter__isnull", False)),
                        fields=("user", "chapter"),
                        name="like_unique_chapter",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Save",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "artwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="ilustra.artwork",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "artwork"), name="save_unique"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(
                fields=("series", "number"), name="chapter_unique_number"
            ),
        ),
    ]
