# Generated by Django 5.2.17 on 2026-09-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilustra', '0001_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watermark_enabled',
            field=models.BooleanField(default=False, verbose_name='marca de agua en mis obras'),
        ),
    ]
