# Generated by Django 5.2.17 on 2026-09-28 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilustra', '0002_profile_watermark_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterpage',
            name='overlays',
            field=models.JSONField(blank=True, default=list, help_text='Globos de diálogo: [{id, x, y, w, text, character, voice, sfx}, …]', verbose_name='viñetas de texto'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='descripción')),
                ('image_url', models.CharField(max_length=1000, verbose_name='imagen')),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('voice', models.CharField(blank=True, choices=[('', 'Automática'), ('grave', 'Grave'), ('aguda', 'Aguda'), ('neutra', 'Neutra')], max_length=10, verbose_name='voz')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='ilustra.series')),
            ],
            options={
                'verbose_name': 'personaje',
                'verbose_name_plural': 'personajes',
                'ordering': ['order', 'id'],
            },
        ),
    ]
